### ISSUE TITLE
Add buttons to explicitly start and stop the trace server

### ISSUE THREAD

**Issue by ankusht-work** [theia-ide/theia-trace-extension#191]
We can consider two options: 

1) Placing the set of buttons under the Trace explorer widget as seen in the image.
<img width="541" alt="Option 1" src="https://user-images.githubusercontent.com/68207987/100772810-b0a35480-33c5-11eb-8fab-1f6501fe1247.PNG">
     
Pros: 
- We are keeping all the logic within the trace plugin so if the plugin is disabled/removed, we don't have to explicitly 
remove buttons specific to this plugin.

Cons : 
- Might clutter the space since we have an open Trace button as well. 
- User can accidentally click the stop button while trying to import (maybe?)
 
     

2) Add buttons to the existing status bar. Once the server is running, the status bar changes to blue color. 
<img width="609" alt="Status_bar" src="https://user-images.githubusercontent.com/68207987/100782136-966f7380-33d1-11eb-9129-ebcf4efdc0dc.PNG">

Pros:
- We already provide notification that the Trace server is offline. 
- Providing the ability to start the server next to the warning is a good user experience I believe.

Cons:
- Might need to explicitly remove buttons from the status bar if the extension is disabled (maybe). Not too sure about this honestly.

**Comment by bhufmann** [comment]
Interesting suggestion of option 2. I like this suggestion. The only thing I feel it might be a bit long to have both strings. Maybe we can have only one String for offline and one for running (similar to "Start in Chrome (theia-trace-extension)")
- "Start trace server" or "Click here to start trace server"
- "Stop trace server" or "Click here to stop trace server"

The offline and running state would be implicit. 

There could be an additional tooltip on the button to give a longer description, e.g. "Trace server is offline. Click here to start trace server"

I agree that the button should be removed when the extension is disabled

**Comment by mirsky-work** [comment]
+1 for Bernd's suggestion to combine the connection _status_ and _action_ strings.

This issue is linked to #184, and I'd also like to point out that the spawned child process will be implicitly terminated when the node backend is sopped.

**Comment by ebugden** [comment]
I disagree with giving front-end users control over the servers. Trace sever management is a separate (and powerful) set of  responsibilities and giving any user this ability breaks several use cases the tool could progress towards (ex. single server, multiple simultaneous clients). More detailed comment on issue #184.

**Comment by bhufmann** [comment]
> I disagree with giving front-end users control over the servers. Trace sever management is a separate (and powerful) set of responsibilities and giving any user this ability breaks several use cases the tool could progress towards (ex. single server, multiple simultaneous clients). More detailed comment on issue #184.

@ebugden @ankusht-work I added reply on issue #184, comment https://github.com/theia-ide/theia-trace-extension/issues/184#issuecomment-736941716.

**Comment by muddana-satish** [comment]
Adding to this discussion, we can have a third option which is a pop up window to the bottom right. Adding screenshots of the VSCode to give an idea of how the pop-up window looks. (Ignore the contents)

![image](https://user-images.githubusercontent.com/70230232/100926271-034d4100-3498-11eb-985c-b0050a878f1d.png)

I believe this is a good option because it catches the user's attention easily. Since the trace server is a requirement for using the trace extension, I think we should alert the user. I do not know if theia supports this popup window. If it does, this is a good option to consider.

Any thoughts on this @bhufmann @ebugden ?

**Comment by ebugden** [comment]
My understanding is that users wouldn't be starting/stopping the trace server often. Ex. Once when they open the tool and maybe restarting it if something crashes/hangs. Can someone think of an situation where a user would want to explicitly stop the trace server?

Maybe it makes sense to put a "Start Trace Server" button directly in the configuration settings #184?

> Since the trace server is a requirement for using the trace extension, I think we should alert the user.

This is a good point. Starting the trace server is a blocking action so the UI should make that clear. Throwing out some quick ideas below for different situations:

**1. Trace viewer server configuration settings are incomplete**, show this:
![image](https://user-images.githubusercontent.com/28311615/100959520-7a142980-34ec-11eb-9bba-58db760468dc.png)

Clicking the the button brings the user to the Trace Viewer Server configuration settings. If valid configuration options are not entered, the "Start Server" button is faded and not clickable:
![image](https://user-images.githubusercontent.com/28311615/100958231-f8bb9780-34e9-11eb-9907-b8a8020394f8.png)

When valid settings are entered, the "Start Server" button turns blue and looks clickable:
![image](https://user-images.githubusercontent.com/28311615/100958375-31f40780-34ea-11eb-8bfd-cc4ed2bafcda.png)

**2. The server is configured, but not started**, show this:
![image](https://user-images.githubusercontent.com/28311615/100959579-9e700600-34ec-11eb-8f47-f922f3640744.png)
or maybe this? ("Configure Server" is still clickable just de-emphasized visually)
![image](https://user-images.githubusercontent.com/28311615/100959704-d9723980-34ec-11eb-8a5f-46e14f53e46a.png)

**3. The server is running correctly** and everything is good to go, show this:
![image](https://user-images.githubusercontent.com/28311615/100957273-24d61900-34e8-11eb-98ac-0a240f303538.png) 

---

> @muddana-satish We can have a third option which is a pop up window to the bottom right.

I think pop-up notifications could still be valuable as extra insurance, but they don't make it explicit that taking action is a requirement.  

They could also be used to notify the users that the server has started successfully (or if the server has crashed).

> @mirsky-work I'd also like to point out that the spawned child process will be implicitly terminated when the node backend is stopped.

I think I'm missing context, do you mean the trace server process will automatically stop when the tool is closed?

**Comment by ankusht-work** [comment]
Maybe it makes sense to put a "Start Trace Server" button directly in the configuration settings #184? ------We had discussed placing a button in the preferences widget but it looks like adding a button in the preferences settings is not supported with the current implementation of preferences API.

**Comment by mirsky-work** [comment]
> I think I'm missing context, do you mean the trace server process will automatically stop when the tool is closed?

Yes. What I meant to say is that (at least for now) we shouldn't worry about explicitly stopping the server or having orphaned processes.

As Ankush mentions, looks like having buttons in the configuration isn't supported (certainly not common). So if we exclude (1), what's outlined under (2), (3) looks good to me.

**Comment by ebugden** [comment]
> So if we exclude (1), what's outlined under (2), (3) looks good to me.

So the current plan is to aim for this for configuring and starting the server? Plus maybe a pop-up to notify the user when the trace server is up and running?
![image](https://user-images.githubusercontent.com/28311615/101111687-b0fc4500-35a9-11eb-93ed-e866d4aa4668.png)

**Detail:** If it's possible to detect that the server is not configured and disable/visually de-emphasize the "Start Server" button that would be the UX cherry on top
![image](https://user-images.githubusercontent.com/28311615/101111992-60391c00-35aa-11eb-801a-11550328572e.png)

# Related situations
* **Crash:** What happens if the server crashes? Do we pop a notification with a button to restart the server? Do we block the user with a button in the side panel similar to above? 
* **Configuration change:** What happens if the user changes the configuration settings while the server is running?
* **Intentional restart:** Do users need a way to intentionally restart the server? Leave that to a command?
* **Stopping:** We don't need a button for stopping the server because it's closed automatically along with the tool.

**Comment by bhufmann** [comment]
My take on this, that the fact that there is a trace server involved for analyzing traces should not need to be known by the user. For the local case, it's just a back-end process that does the data processing. Starting and stopping of a the trace server should be handled by the for the user.

I see the local trace server similar to the language and debug server that is used for coding and debugging. The Language server and debug server are started for the user when needed (e.g. opening a file) and stopped when not needed anymore. 

The language server (LS) can be restarted if needed (I recently had to do it for the typescript LS) with "F1" and "Typescript: Restart TS Server". (CTRL-SHIFT-P works too).

- Is it possible to start the trace server automatically when the first trace is opened? Or are there limitations at the moment that doesn't allow that? @ankusht-work do you have any information about that?
- Once the server has been started for the first trace, then the monitor is started that detects if the connection to trace server goes down.  In the case the trace server application can't be found, then there should be an notification for the user and with the option to configure the trace server.
- Crash: If the trace server crashes, the status line notifies the user. Provide a hint on how to start the server (Press F1 + "Start trace server". This requires a command "Start trace server".
- Stop the trace server when the tool closes. No need for a button. We can provide the command through F1 and "Stop trace server". Stopping the trace server the monitor should stop as well.
- Configuration change: I think the configuration should be provided for the user. Changing them should only be done in exceptional cases. Maybe it should only get in effect when the trace server is started the next time after the configuration change.

**Comment by ebugden** [comment]
> My take on this, that **the fact that there is a trace server involved** for analyzing traces **should not need to be known by the user**.

@bhufmann I strongly second your take for the local server case. Thanks for the sanity check. This would mean:

* No buttons for starting/stopping
* No message in the status bar saying that the server is running
* Notify the user only if something requires their action

---

> **Crash:** If the trace server crashes, the status line notifies the user. Provide a hint on how to start the server (Press F1 + "Start trace server".

Since the tool would be starting the server automatically, could the tool try restarting the trace server automatically? And then notify the user if "The trace server is not responding and could not be restarted."

---

> **Configuration change:** I think the configuration should be provided for the user. Changing them should only be done in exceptional cases. 

What would automatic configuration require? That the trace server is always installed in a specific place?

---

> In the case the trace server application can't be found, then there should be an notification for the user and with the option to configure the trace server.

Is it possible to attempt to start the server automatically as soon as both fields are complete without using a button to initiate the action?
