### ISSUE TITLE
Consider changing the term "experiment"

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#194]
It's worth considering whether the term "experiment" should carry over from Trace Compass into the trace viewer. There are a few disadvantages with this term from a user experience perspective that could confuse users and harm adoption. 

* What were the goals and purpose behind this term?

# Some UX disadvantages
* **It's an extra term:** Users need to understand "experiment" before they can use the tool properly (since the core of the trace viewer is being able to combine and compare several data sources). 
* **It's tool-specific:** My understanding is that "experiment" is specific to the Trace Compass ecosystem and that it is not used throughout the tracing community. So this extra learning is only useful inside the TC ecosystem.
* **It's potentially misleading:** An "experiment" sounds like it comes from an intentional benchmark when it could just as easily contain a post-crash dump that happened during standard operation.

# Is there a more intuitive or self-evident term that could be used? 
**Quick ideas:** Trace group, data group. I can picture "Open Data Group" or "Save files as Data Group".

My understanding is that an "experiment" is a collection of data (traces, logs, etc.) that is currently being analyzed together: 
* It's a collection of evidence that can be from different times, different systems, different applications, etc. 
* In theory, the only characteristic linking the data is that the user decided it is relevant for these to be viewed together. They want to group them to make it easy to locate and compare the different files. 
* A file could be part of several "experiments".

**Design questions:** What is an experiment? What is the functional purpose of an experiment? What are all the different types of data sources that can be included in an experiment? What does an experiment typically contain (what types of data sources, how many of each)?

# What would be the consequences of using a different term?
Using a different term than Trace Compass could cause some issues. Ex. Trace Compass users could be initially thrown off when switching to the trace viewer. 

---

CC: @bhufmann @tahini @MatthewKhouzam

**Comment by bhufmann** [comment]
@ebugden thanks for initiating this discussion. I''ll try to give some clarifications below. 

There have been several attempts in the community and internally to change the term "Experiment" to somethings else. But in the end there hasn't been any suggestion so far that seems to fit better and had better acceptance. One suggestion was to call it "Project", however projects in the Eclipse IDE have different meaning and was not suitable.

I'm not attached to that term either and I'll gladly use something else in the Theia trace extension if we find a term that is clearer and we can get better acceptance.

One important characteristic of an experiment is, that in an experiment the trace events from each trace are analyzed in chronological order (time-ordered). For example, if you look at the events table you will see the trace events sorted by time. So, an experiment is not just a set or group of traces. 

See below for some inline replies.

> It's worth considering whether the term "experiment" should carry over from Trace Compass into the trace viewer. There are a few disadvantages with this term from a user experience perspective that could confuse users and harm adoption.
> 
>     * What were the goals and purpose behind this term?
> 
> 
> # Some UX disadvantages
> 
>     * **It's an extra term:** Users need to understand "experiment" before they can use the tool properly (since the core of the trace viewer is being able to combine and compare several data sources).
> 
The goal in Theia is to hide the concept of experiments from the user as much as possible. Experiments should be created for the user by the tool when possible. When not possible, it needs to be straight-forward for the user to create experiments. For example, for LTTng sessions with a kernel and a ust trace, when the user selects the UST trace only an experiment with the UST trace is opened. When the user opens the kernel trace, then only the experiment with kernel trace is opened. If the user selects the LTTng session, an experiment with both kernel and UST trace is opened. 

>     * **It's tool-specific:** My understanding is that "experiment" is specific to the Trace Compass ecosystem and that it is not used throughout the tracing community. So this extra learning is only useful inside the TC ecosystem.
> 
The term Experiment is Trace Compass specific, but the concept of analyzing multiple traces time-ordered is common. In the Theia trace extension we'll need something similar.

>     * **It's potentially misleading:** An "experiment" sounds like it comes from an intentional benchmark when it could just as easily contain a post-crash dump that happened during standard operation.
> 
> 
> # Is there a more intuitive or self-evident term that could be used?
> 
> **Quick ideas:** Trace group, data group. I can picture "Open Data Group" or "Save files as Data Group".
> 
What you describe here is the data for an investigation. An investigation can have one or more experiments, different other files and logs.

> My understanding is that an "experiment" is a collection of data (traces, logs, etc.) that is currently being analyzed together:
> 
>     * It's a collection of evidence that can be from different times, different systems, different applications, etc.
Yes, it's to correlate traces from different sources, but time-ordered. 
> 
>     * In theory, the only characteristic linking the data is that the user decided it is relevant for these to be viewed together. They want to group them to make it easy to locate and compare the different files.
Comparison is another aspect. Experiments are not typically not used to compare different traces, because of the time difference.  It could be done if time offsets are applied to the traces to have under the same timeline.

> 
>     * A file could be part of several "experiments".
If you mean experiment configuration files (e.g. custom colorings), then yes. Other files from the traced system are not part of the experiment, it would on a higher level (investigation).
> 
> 
> **Design questions:** What is an experiment? What is the functional purpose of an experiment? What are all the different types of data sources that can be included in an experiment? What does an experiment typically contain (what types of data sources, how many of each)?
* Experiment is a collection of heterogeneous traces where the trace events of each trace are analyzed chronological order.
* Purpose to is correlate traces from different sources 
* There are many types of data sources depending on the system being traced: Network traces, HW traces, operating system traces, user space traces, traces from multiple different nodes and others. The idea is to correlate heterogeneous traces (different sources and format) together.
* How many traces are in an experiment depends on the investigation.  An experiment contains one or more traces.

> # What would be the consequences of using a different term?
> 
> Using a different term than Trace Compass could cause some issues. Ex. Trace Compass users could be initially thrown off when switching to the trace viewer.
> 
As long as we keep the functionality it should be ok to use a different term.

**Comment by ebugden** [comment]
> In an experiment the trace events from each trace are analyzed in chronological order (time-ordered). For example, if you look at the events table you will see the trace events sorted by time. So, an experiment is not just a set or group of traces.

> There are many types of data sources depending on the system being traced: Network traces, HW traces, operating system traces, user space traces, traces from multiple different nodes and others. The idea is to correlate heterogeneous traces (different sources and format) together.

Ah ok! I was missing the time-ordered concept. So an experiment is a richer trace of a specific period in time for a specific system that is created by combining several heterogenous traces from different trace data sources in that system. 
* It only contains trace files (from different trace data sources, possibly of different formats).
* It only makes sense to create an experiment with data that comes from the same system and time period.

# Brainstorming & Inspiration
**Maybe we don't need a special name for these merged traces.** The combined result is, in practice, still a trace file. It allows for richer analyses, but the user interacts with it (visualizes, analyzes) exactly like they would interact with a standard trace file. 
* Are there situations/use cases that would justify the user needing to understand the difference between an experiment and a standard trace file?  

**Since many users are probably familiar with git (or merge sort), maybe we could incorporate the term "merge".** 
* Creating an experiment is like merging two git branches (the commits are placed in chronological order). 
* Ex. "Select traces to merge", Select + Right-click: "Merge traces A, B and C", Text above file list: "Viewing merged trace of: <file list>"

**It also reminds me of that image processing technique of combining several low resolution images into a higher resolution image**, but that's called "stacking" which I feel doesn't communicate the time-ordered aspect clearly. Trace "stacking" Feels more like superposition rather than combination.

Thesaurus inspiration: Merge, combine, fuse, join, unite

**Comment by mirsky-work** [comment]
> Maybe we don't need a special name for these merged traces. The combined result is, in practice, still a trace file. It allows for richer analyses, but the user interacts with it (visualizes, analyzes) exactly like they would interact with a standard trace file.

In TC it's possible to select and open individual traces within an experiment. Not sure how much it's used in practice, but I can think of a scenarios where it can be useful. I also find the term "Experiment" confusing and would like to propose "Trace Session" or "Trace Aggregate". While longer than just "Experiment", it conveys the intention better, IMHO.

**Comment by bhufmann** [comment]
> # Brainstorming & Inspiration
> 
> **Maybe we don't need a special name for these merged traces.** The combined result is, in practice, still a trace file. It allows for richer analyses, but the user interacts with it (visualizes, analyzes) exactly like they would interact with a standard trace file.
> 
>     * Are there situations/use cases that would justify the user needing to understand the difference between an experiment and a standard trace file?
> 
> 

I'm not sure anymore. Maybe by definition, a trace consists of one or more trace files. If you look at a CTF trace, it's already the case, i.e. a CTF trace is a metadata file and set of binary files. 

I have a suggestion for the MVP. What if we go with this definition, that a trace is one or more trace files and in the front-end there is no mentioning of the term Experiment whatsoever. Behind the scene we still work with experiments but that's hidden from the user. For example, the Trace Explorer will show "Open Traces" instead of "Open Experiments". 

Any thoughts? @ebugden @mirsky-work

**Comment by mirsky-work** [comment]
> Behind the scene we still work with experiments but that's hidden from the user. For example, the Trace Explorer will show "Open Traces" instead of "Open Experiments".

It certainly makes sense for the current implementation and I think that's what we should go with for the MVP.

It might become confusing if we'd like to allow selecting different "traces" in an experiment that contains recordings from different sources, but perhaps it can be addressed by filtering capabilities.

**Comment by ebugden** [comment]
# Not using "experiment" in the MVP?
> for the MVP. What if we go with this definition, that a trace is one or more trace files and in the front-end there is no mentioning of the term Experiment whatsoever.

Yes, making no mention of experiments would be simplest for the user, if that solution makes sense.

> Behind the scene we still work with experiments but that's hidden from the user.

**What would that not mentioning experiments look like in practice for the MVP?** 
* If it's possible to simultaneously open multiple traces and multiple experiments:
  * How are experiments (and the traces they are made of) displayed in the tool vs. individual trace files? 
  * Are experiments displayed as a single file (file components hidden) or are all the files that they're composed of shown?
* Are experiments formed automatically? 
  * If yes, when and based on what criteria? (ex. If a user simultaneously opens several mergeable trace files does it automatically form an experiment?) 
  * If not, how do users know they can view certain groups of trace files as a merged trace? 

Technical question: When an experiment is formed with several traces (merging all the trace files) is this something that is done live every time the experiment is opened? Is an experiment basically a list of paths to the trace files it is composed of? Or is it done once and a copy of this merged trace is saved somewhere? Are copies of all the traces stored together somewhere? 

---

> **mirsky-work:** In TC it's possible to select and open individual traces within an experiment. Not sure how much it's used in practice, but I can think of a scenarios where it can be useful.

I think we'll be able to still handle this case nicely. Depending on how experiments are stored, maybe users could explicitly open the file they want to see. Or I can imagine being able to show an experiment in a way that allows users to select/deselect different files like layers in Photoshop. 

# Alternatives to "experiment"

> **mirsky-work:** would like to propose "Trace Session" or "Trace Aggregate".

* **Trace Session**: This feels more like it's characterizing a time period or an environment rather than a product/result. Also I think LTTng already uses the idea of a tracing session. Could this cause confusion?
* **Trace Aggregate**: Aggregate feels more accurate: "a whole formed by combining several (typically disparate) elements". It feels technical/advanced, but that could be a valid decision if you want to communicate that it's an advanced feature that beginner's shouldn't be using. 

Since an experiment is treated as a single trace, I like the idea of putting emphasis on how the resulting "trace" is formed and less emphasis on an experiment being a group (since it's treated as a unit). Some additional ideas:
* **Merged Trace:** Suggests that the combined result is sorted in time since this is how git merge and merge sort use the term.
* **Combined Trace**, **Composite Trace**: More simple ways of saying "Trace Aggregate"? 

# Allow grouping traces for quick access during investivation? 

> > **ebugden:** **Quick ideas:** Trace group, data group. I can picture "Open Data Group" or "Save files as Data Group".
> 
> **bhuffman:** What you describe here is the data for an investigation. An investigation can have one or more experiments, different other files and logs.

Separate to the concept of an experiment, I think it could be useful to group traces/experiments related to a particular investigation. Ex. 3 different examples of the same problem happening on a system at different times. This could save "spinup" time when getting back into looking at a particular problem. I'll probably create an issue to discuss this idea.

**Comment by tahini** [comment]
Can this be closed?

**Comment by bhufmann** [comment]
> Can this be closed?

Yes, I think so. Any other updates related to "Experiments" will be tracked in different issue trackers.

**Comment by ebugden** [comment]
Dropping some related thoughts here. 

There are **2 distinct use cases for grouping traces:**
1. **Forming a complex trace:** Several layers of traces taken simultaneously (kernel+userspace+network), could span several nodes. Goal: To create a richer image of a particular span of time
2. **Forming a trace group (for ease of comparison/reference):** Collection of traces that aren't necessarily taken simultaneously. Ex. Traces from before/after applying a patch, 5 instances of the same issue, etc. Goal: Comparison, clustering/convenience

I think this is why it was so difficult to find an alternative name for experiments — we were trying to find one name that covers two different use cases.

For clarity, it may make sense to separate these two use cases for the user (even if the implementation is identical in the background). I may create a separate issue to discuss this in the future.

----
CC: @ssmagula
