### ISSUE TITLE
Rename Opened Traces widget and commands

### ISSUE THREAD

**Issue by PatrickTasse** [theia-ide/theia-trace-extension#277]
With the latest changes, the 'Opened Traces' widget in the Trace Viewer view will show the list of every trace that has ever been opened in the trace server (using 'Open With > Trace Viewer' menu in Explorer or 'Open Trace' dialog in Trace Viewer) and that has not been deleted. When a trace tab is closed, the trace remains opened in the trace-server and still appears in the 'Opened Traces' widget. But after a trace-server restart, the trace may be closed in the trace-server and it will still appear in the client.

Furthermore, each trace in the 'Opened Traces' widget has a context menu with three commands:
- Open Trace
- Close Trace
- Delete Trace

The Open Trace command opens the trace tab and if necessary, opens the trace in the trace-server
The Close Trace command closes the trace tab but has no effect on the trace-server
The Delete Trace command removes the trace from the trace-server workspace (links, supplementary files) but does not delete the actual trace files.

This issue is to consider whether the widget title 'Opened Traces' and the three command names are still appropriate and have an intuitive meaning for the users.

**Comment by ebugden** [comment]
This is somewhat tangential, but **why not just have "Remove Trace / Delete Trace"** in the context menu? 
 * **"Close Trace"** (Hide Trace) is covered by closing the open tab (arguably this could be included in context menu to avoid searching for the tab to close).
 * **"Open Trace"** (View Trace) is covered by clicking on the trace on the list.

----

### Widget name thoughts
* **"Traces"** : My favourite. Simple and the ambiguity allows for flexibility without lying to the user (ex. Traces that aren't being viewed could be faded but still in the list).
* **"Opened traces"** : The traces in the list aren't necessarily opened.
* **"Available traces"** : There could be available traces that aren't on this list.
* **"Recently opened"** : Not necessarily. Just previously opened.

An option we can consider when renaming is white lying to the user. Well, misrepresenting reality in a way that makes their life less confusing, but isn't technically accurate. Ex. Using the same label for two different operations that feel similar for the user, but actually have different implementations (like label overloading instead of function overloading)

----

> **PatrickTasse:** 'Opened Traces' widget in the Trace Viewer view will show the list of every trace that has ever been opened in the trace server and that has not been deleted.

Listing all previously opened traces makes me nervous, but I'm not sure why. Could someone point me to where the rationale behind this decision was explained?

* Should there at least be an expiry on how long the traces sit there if they're not explicitly deleted?

**Comment by muddana-satish** [comment]
> This is somewhat tangential, but **why not just have "Remove Trace / Delete Trace"** in the context menu?
> 
> * **"Close Trace"** (Hide Trace) is covered by closing the open tab (arguably this could be included in context menu to avoid searching for the tab to close).
> * **"Open Trace"** (View Trace) is covered by clicking on the trace on the list.

@ebugden  Usually, all the actions that you want to do on a file are available in the context menu. That is the reason why I have added these as part of context menu. Is there a specific reason why we do not want to have them in the context menu?

**Comment by ebugden** [comment]
PR #541 uses the language "Remove Trace" for the action of deleting a trace group from the trace viewer and from the trace server (without deleting the actual trace files). The current widget labels this same action as "Delete Trace". The label in this widget should be consistent with the tooltip and the confirmation message in #541.

Current widget (Delete):
![image](https://user-images.githubusercontent.com/28311615/140953595-9ea2d40b-6fb0-498b-bc22-5e30112d5568.png)

PR #541 (Remove):
![image](https://user-images.githubusercontent.com/28311615/140954508-d00a20a0-6777-44d0-97e5-4dcdee760d2b.png)
