### ISSUE TITLE
Improve timegraph chart navigation

### ISSUE THREAD

**Issue by muddana-satish** [theia-ide/theia-trace-extension#299]
Opening this thread to discuss about the consistency of the commands that has to be executed with buttons vs command palette.

How to support undo-redo options and more..

Edit: I believe the following are few of the options that should be shown as buttons in trace extension. (available in Trace Compass toolbar)

- Reset the Time Scale to Default
- Select Previous State Change/ Select Next State Change
- Select Previous Resource/ Select Next Resource
- Zoom In/ Zoom Out

What would be the ideal place to have these buttons in trace extension? 

@ebugden Any thoughts on this?

**Comment by ebugden** [comment]
I don't understand what the focus of this issue is. Is it to:
* "discuss about the consistency of the commands" Not sure what you mean here
* To decide if commands should be available via buttons or via the command palette?
* To create buttons for existing operations?
* To propose new operations?

Here's what I would guess: There are a set of command palette commands (already implemented) that perform the operations listed above and you'd like to assign them to buttons? Is this accurate? If this isn't correct, please edit the issue description to clarify.

**Comment by muddana-satish** [comment]
@ebugden Sorry for not posting the details clearly. I hope this explanation helps.

Currently most of the actions(like zoom-in/out, state navigation) on the timegraph chart (Resources View) are the keyboard shortcuts. It's hard for a new user to find out all these shortcuts. For this reason, it's good to have dedicated buttons or toolbar icons for each user action. 

The below screenshots show the toolbar icons for the resources view in Trace Compass.

![photo_2021-03-30 12 49 18](https://user-images.githubusercontent.com/70230232/113033255-7325bc80-9156-11eb-9ced-616536d4a7f1.jpeg)

![image](https://user-images.githubusercontent.com/70230232/113027486-c34d5080-914f-11eb-8743-77f27832e038.png)

Also, there are a few features that are not implemented in theia like 'Reset the Time Scale to Default' and 'Undo/Redo'. The idea is to have similar icons available in theia for the supported user actions.

What are your thoughts on this? 

If we plan to have these icons, what would be the right place in the UI as we share the time axis across the different charts, and all the actions may not be applicable for all the charts. 

If we cannot have it in the UI(for any reason), is it good to have any of these as part of command palette? 

Please share your thoughts.

**Comment by muddana-satish** [comment]
Adding @ssmagula to the discussion.

**Comment by ebugden** [comment]
Ahh ok I understand now! Can you adjust the title to "**Improve chart navigation**"?

Here's what I understand: Right now, users can only navigate using tricky-to-learn keyboard shortcuts. We're deciding:
* Which actions should be added for comfortable chart navigation? 
* What's the most intuitive way to allow users to perform these actions? (buttons, command palette commands, etc.)

----

> **muddana-satish:** Currently most of the actions(like zoom-in/out, state navigation) on the timegraph chart (Resources View) are the keyboard shortcuts. It's hard for a new user to find out all these shortcuts.

Yesss! I 100% agree this is a problem. Users had a hard time with this during @ssmagula's user tests so, based on this, we've prioritized designing good solutions for two aspects of navigation:
* Zoom in/out #330
* Pan left/right #331

These aren't the highest priority issues for us right now though. We'd probably be getting to these in a couple weeks. **If you guys were planning to implement this now let's have a meeting to coordinate/adjust priorities.** 

----

> **muddana-satish:** What would be the ideal place to have these buttons in trace extension?

In short, I don't have an answer right now. Comfortable chart navigation is a complicated design problem since trace data spans 6+ orders of magnitude which is a huuuge range. 

We're not even sure if these will actions will be buttons (vs. scrolling, dragging, arrows, etc.)

----

> **muddana-satish:** I believe the following are few of the options that should be shown as buttons in trace extension. (available in Trace Compass toolbar)
> * Reset the Time Scale to Default
> * Select Previous State Change/ Select Next State Change
> * Select Previous Resource/ Select Next Resource
> * Zoom In/ Zoom Out
>
> [...] Also, there are a few features that are not implemented in theia like 'Reset the Time Scale to Default' and 'Undo/Redo'.

Can you describe with screenshots (or show with a quick video) what you mean by:
* Select Previous State Change/ Select Next State Change
* Select Previous Resource/ Select Next Resource

I don't know what a "State Change" or a "Resource" are in this context.

**Comment by bhufmann** [comment]
We need to distinguish between global buttons, whose actions are applied to all graphs under the time axis and buttons that are graph specific. Zoom in and out, reset zoom, maybe global filtering/searching are to applied to all the graphs. These buttons should be available only once, maybe in a global toolbar under toolbar.

Other buttons, e.g. next/previous state/resource/markers, are specific to certain graphs and might not be valid for others. Next and previous state is for example not applicable in XY charts. They are also depending on e.g. row selection, e.g. the outcome come of pressing next and previous state is different from row to row. 

I think the buttons should not be repeated either per graph (like in Trace Compass) to avoid loosing vertical real estate.  

I also, think that we should start with a limited number of buttons globally first (Zoom-in/out, reset Zoom). Then we can "carefully" add others if they make sense.

**Comment by ebugden** [comment]
> **bhufmann:** we should start with a limited number of buttons globally

I agree. I'd like to be extremely conservative with the buttons we add. 

I think it's possible to provide comfortable basic navigation without buttons that are always showing (ex. [Zooming in Perfetto](https://github.com/theia-ide/theia-trace-extension/issues/330#issuecomment-818921169)), but I think buttons could be good quick fix for now since users just have hot keys.

**Comment by mirsky-work** [comment]
#394 implements the requirements that were under consensus (zoom in, zoom out, reset zoom). Closing this issue, if there will be further requirements we'll create a new one.
