### ISSUE TITLE
Add a setting in the UI to specify trace server CLI arguments

### ISSUE THREAD

**Issue by mirsky-work** [theia-ide/theia-trace-extension#479]
The default workspace location is in the user's home folder (~/.tracecompass-webapp). That can be an issue with NFS mounted home folders that can fill-up quickly, when opening very large traces, making the system slow and unusable. There's a way to override the default workspace path, by passing it with `-data` to the trace server. There should be a UI setting added to make it possible to change it from the UI (under the existing Trace Viewer section).

**Comment by hriday-panchasara** [comment]
Here is a mockup of the server CLI args settings. Could you suggest what I could put for the setting name, description, and maybe a default value?
![Screen Shot 2021-11-09 at 3 30 31 PM](https://user-images.githubusercontent.com/92893187/141008286-4dd2bd4f-f74c-4bdc-a8d2-6240ab6ee683.png)

**Comment by mirsky-work** [comment]
Thanks for putting up the mockup. I suggest placing the new setting at the end, after "Trace Server: Port", and rephrasing as follows:

Trace Server: Arguments (optional)
Specify optional trace-server command line arguments

**Comment by ebugden** [comment]
For comparison, is the way the server port specified also Trace Compass Server specific?

Summary attempt to make sure I understood correctly: 
* This issue's main goal is to be able to specify the folder where the Trace Server reads traces and creates trace groups (experiments), etc.
* The most user friendly way to do this would be to add a settings field to specify the trace folder, but we can't do that because the "-data" argument is specific to the Trace Compass Server. Instead, we need to allow a more general way of specifying server arguments.

**Comment by bhufmann** [comment]
> For comparison, is the way the server port specified also Trace Compass Server specific?
> 
> Summary attempt to make sure I understood correctly:
> 
>     * This issue's main goal is to be able to specify the folder where the Trace Server reads traces and creates trace groups (experiments), etc.
> 
>     * The most user friendly way to do this would be to add a settings field to specify the trace folder, but we can't do that because the "-data" argument is specific to the Trace Compass Server. Instead, we need to allow a more general way of specifying server arguments.

Yes, I the current setting of the port is Trace Compass server specific and the port is specified as command-line parameter, i.e. it adds the following command-line: `-vmargs -Dtraceserver.port=${port}`.

So, I suggest to have a generic way to add command-line parameters that are independent to the server implementation. Maybe having a free-text field that is added when spawning the server.

**Comment by hriday-panchasara** [comment]
> Thanks for putting up the mockup. I suggest placing the new setting at the end, after "Trace Server: Port", and rephrasing as follows:
> 
> Trace Server: Arguments (optional) Specify optional trace-server command line arguments

Not sure if I'll be able to alter the ordering since all settings are arranged in alphabetical order. Let me know if this works instead:
![Screen Shot 2021-11-10 at 10 24 26 AM](https://user-images.githubusercontent.com/92893187/141152296-9a8a3821-a1b9-45f4-ac51-dc3c54414c5c.png)

Also a little confused about how the command-line parameters should be integrated when invoking the trace server, would  the args look something like:  `-vmargs -Dtraceserver.port=${port} -optionalParams`

**Comment by ebugden** [comment]
Hold on for a moment @hriday-panchasara it looks like the implementation approach could shift.

> > **ebugden:** For comparison, is the way the server port specified also Trace Compass Server specific?
> > Summary attempt to make sure I understood correctly:
> > 
> > * This issue's main goal is to be able to specify the folder where the Trace Server reads traces and creates trace groups (experiments), etc.
> > 
> > * The most user friendly way to do this would be to add a settings field to specify the trace folder, but we can't do that because the "-data" argument is specific to the Trace Compass Server. Instead, we need to allow a more general way of specifying server arguments.
> > 
> 
> **bhufmann:** Yes, I the current setting of the port is Trace Compass server specific and the port is specified as command-line parameter, i.e. it adds the following command-line: `-vmargs -Dtraceserver.port=${port}`.
> 
> So, I suggest to have a generic way to add command-line parameters that are independent to the server implementation. Maybe having a free-text field that is added when spawning the server.

To build on this, I think we could either:
* **Have both settings Trace Compass Server specific (port, trace folder):** I don't think this is a bad choice at this point since I assume the defaults for settings (path and port) are also hardcoded into the client and Trace Compass Server specific. This would be quickest to add and keep things consistent.
* **Commit to generalizing for any trace server:** Add a generic command line arguments field where port and trace server can be specified. Have the trace server send over port and trace folder defaults? (Hardcoded front end defaults isn't server agnostic either...)

**Comment by mirsky-work** [comment]
@ebugden, that's a fair point - we do make some assumptions about how the server is implemented (see the snippet below from startTraceServer). However, having a free text field, that will be appended to the invocation string, has the benefit of allowing to specify other arguments as well. If we want to be completely server-agnostic, the settings should contain just _Trace Server Path_ and _Tracer Server Arguments_ (set by default to '-vmargs -Dtraceserver.port=8080').

@bhufmann, what do you think? 

A snippet from trace-server-service.ts
```
const server = spawn(path!, ['-vmargs', `-Dtraceserver.port=${port}`]);
```
