### ISSUE TITLE
Use the Theia backend to automatically start the trace server

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#53]
On basic installations, there may not be a trace server running separately from theia. Admins need to make sure such a server exists and is started. The Theia default installation should include fetching and starting the web server.

The trace server should also be configurable, so if there's a remote server running, it should all point to it.

**Comment by ebugden** [comment]
@bhufmann @ankusht-work @mirsky-work Could we group our thoughts on here? I'm thinking about how to automatically start/manage the trace server and looked at [trace-server-status.ts](https://github.com/theia-ide/theia-trace-extension/blob/master/viewer-prototype/src/browser/trace-server-status.ts) for inspiration.

My first reflex was to reimplement the [handleOffline( )](https://github.com/theia-ide/theia-trace-extension/blob/a57e90032868818e31091996584385e5e0e49d09/viewer-prototype/src/browser/trace-server-status.ts#L130) function in the TraceServerConnectionStatusService to start/restart the server.

The new handleOffline( ) could be loosely inspired by the [openTrace( )](https://github.com/theia-ide/theia-trace-extension/blob/a57e90032868818e31091996584385e5e0e49d09/packages/base/src/trace-manager.ts#L73) function in [trace-manager.ts](https://github.com/theia-ide/theia-trace-extension/blob/a57e90032868818e31091996584385e5e0e49d09/packages/base/src/trace-manager.ts) and try restarting the server a limited number of times with a counter. 

Eventually [schedulePing( )](https://github.com/theia-ide/theia-trace-extension/blob/a57e90032868818e31091996584385e5e0e49d09/viewer-prototype/src/browser/trace-server-status.ts#L38) could be also changed to use @tahini's new server ping instead of using fetchExperiments( ) (at line 44) to check if the server is alive.

**Comment by ankusht-work** [comment]
For starting the server automatically for the user I have listed down all the scenarios that I could think of. @tahini @bhufmann @ebugden @mirsky-work Please let me know your thoughts. 

- Remove the start and stop button from the status bar. Add a text field in the status bar indicating if the server is offline or online. 

- Upon clicking 'OpenTrace' from the trace viewer tab or 'Open with -> Trace Viewer' context menu", check if the server is running. If the server is not started then read the default values of path/port from the preferences and spawn the server.

- If the user tries to modify the value in the path or port preferences, we first kill the server that is running and spawn the server with the new values. Add a dialog message to notify the user about the same.

- Toast messages can be used to provide information about the trace server and the port it is running on.

- Clean exit: When a user exits from the theia-trace-extension we gracefully kill the trace server as well.


- Outside theia's instance: If the user decides to start the server externally then the responsibility lies on the user itself to kill the server upon exit.
 ( Basically, if you trust us then we take care of everything but if you start the server outside then it's your responsibility).

**Comment by ebugden** [comment]
@ankusht-work After a quick read, looks good to me.

> **ankusht-work:** Add a text field in the status bar indicating if the server is offline or online.

If we're imitating the transparency of a debug server for the local use case, maybe we could skip putting a server status message online or offline in the status bar and use toast messages for server status changes. In the final product, the user wouldn't be annoyed with tons of toast messages because server status changes shouldn't happen in normal use.

**Comment by ankusht-work** [comment]
Hi @ebugden : Good point, however, the toast messages will disappear after a set time interval. I think having a permanent visual indication of some sort that a particular server is running will make more sense in my opinion. If the user reloads the browser tab, the server status message will still be there.

**Comment by ebugden** [comment]
Ah, fair point on the disappearing message being bad. I'm going to pop my suggested design criteria here and you guys can decide which implementation fits best.

**Clearly communicate critical information to the user:** If some problem is preventing the user from using the tool as expected (ex. offline server), there should be a permanent and obvious message that tells them what is wrong. 
* **"Server online" isn't critical info:** Especially for the one-server-per-user use case, users don't need to constantly know when the server is working properly because no action is required from them. It mainly adds visual noise.   
* **The status bar isn't obvious enough for critical info:** When the server is offline, the trace viewer essentially becomes unusable, but my intuition is that many users who weren't involved in development won't notice a subtle status bar saying "Trace server offline" (This claim can be verified in @ssmagula's internal user tests). 
* **If possible, direct users towards how to solve the problem:** Should they try manually restarting the server? Adjusting server configuration?

----

@tahini What actions become impossible if the trace server is offline? Is it's not possible to open new traces and new analyses, but if the analysis is already open it's completely functional? (I'm trying to gage how much of a critical problem an offline server is.)

**Comment by bhufmann** [comment]
@ankusht-work I think it will be good next improvement for this area. I have some comments. 

- I agree with @ebugden, that we don't need to keep showing that the server is online. The language server or debug server doesn't show that either. 
- I think showing on the status bar that the server got offline is good, but only after the server has been started before or it was determined the sever is online (at startup).
- I think the periodic heath check to see if server is online, should only be done after the server has been start successfully once or it has been determined that the sever is online (at startup).  Doing the periodic HTTP request without starting the server will use unnecessary resources. (in case user doesn't do trace analysis)
- I think we can keep the command to stop/start and users can do it using CTRL+SHIT+P. That's more for power users

Bernd

**Comment by bhufmann** [comment]
@ebugden, some reply to your comment:

>What actions become impossible if the trace server is offline? Is it's not possible to open new traces and new analyses, but if the analysis is already open it's completely functional? (I'm trying to gage how much of a critical problem an offline server is.)
>
If the trace server is offline, nothing can really be done even if the analysis is already open because new data will be fetch from the backend when, for example, navigating or zooming in the trace.

**Comment by ebugden** [comment]
Fixed by #298
