### ISSUE TITLE
Investigate if the theia trace extension could be a vscode plugin

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#96]
Since Theia now fully supports vscode plugins, if this extension could be done entirely within the API of the vscode extension, it would be the ideal way to go as the trace viewer could be made available to vscode users as well as to theia's without requiring recompilation.

**Comment by tahini** [comment]
@delislesim do you have any idea on this? Have you investigated it at some point?

**Comment by tahini** [comment]
@ebugden for the record

**Comment by delislesim** [comment]
@tahini Yes I investigated this at some point. I think it is possible to achieve that if Theia supports vscode Webview API. It might requires some refactoring on theia-trace-extension to extract the trace viewer part, but should not be difficult since I tried to decoupled the viewer from Theia, since it was my secret plan all along to make the trace viewer work on other platform. 

During my previous investigation, I came to the conclusion that these API: [Custom editors](https://code.visualstudio.com/api/extension-guides/custom-editors) and [Webview](https://code.visualstudio.com/api/extension-guides/webview) are what your are looking for. I also know that it is possibly to run a react app inside the Webview.

**Comment by bhufmann** [comment]
When investigating this, we need to look also at the local vs remote case, trace detection service and IDE integration. In the end, we need to keep the components modular, then it will be easier to integrate with different environments.

**Comment by delislesim** [comment]
> When investigating this, we need to look also at the local vs remote case, trace detection service and IDE integration. In the end, we need to keep the components modular, then it will be easier to integrate with different environments.

In your case, trace detection and IDE integration should be completely independent from the trace viewer, you can see the viewer as a component that only receive for example a tsp client and a trace URI at creation. Maybe your trace viewer could expose a small interface to receive messages and sending messages to integrate with the IDE like vscode and Theia does to communicate between Webview

**Comment by babyadoresorange** [comment]
I went through the Webview API and it seems to me it isn't suitable for TraceCompass imho.
The Webview's content is forced removed whenever it goes to the background. In order to persist state, we would have to call `vscode.setState` and `getState` to retrieve the state when it goes back to foreground.

This is the function `setState`
![image](https://user-images.githubusercontent.com/22086462/87734491-c0b4f180-c7a0-11ea-9020-f797cc68d11d.png)

So that means everytime it goes to background and back TraceCompass will have to serialize and deserialize its entire state (including millions trace points), which is very costly in this case.

**Comment by tahini** [comment]
> In your case, trace detection and IDE integration should be completely independent from the trace viewer, you can see the viewer as a component that only receive for example a tsp client and a trace URI at creation. Maybe your trace viewer could expose a small interface to receive messages and sending messages to integrate with the IDE like vscode and Theia does to communicate between Webview

I probably read, but did not process @delislesim's comment. But by following vscode's API and software design's best practices, this is exactly what the implementation naturally flowed towards. Trace detection is done by a component that runs wherever the workspace resides (vscode/theia backend), while the trace viewer component simply receives a trace-server URL to create the TspClient and the experiment json object to make requests for outputs. The client has no knowledge whatsoever about any file system or files or even trace details, it's just a "dumb" trace viewer.

By the way @delislesim, your "secret plan" to make the trace viewer work on other platform worked like charm! Migrating to vscode extension was a breeze once the hardware for the new platform was set ;-) Kudos to you and others who worked on the initial repo!

**Comment by tahini** [comment]
After investigation, the trace extension _will_ become a vscode extension. Work has started with 6fdad143 to split the repo in sub-packages that can be used both in a theia or vscode extension. Closing this issue here.
